### ISSUE TITLE
해당 어플의 기능 개선에 관련 문의

### ISSUE THREAD

**Issue by Tianea2160** [yjyoon-dev/kw-library-wearos#14]
해당 어플을 실제 사용함으로써 생각되는 개선점을 적습니다.
- 큐알 코드 갱신이 너무 어렵습니다.
  - 사용자 학번, 비밀번호, 전화번호를 입력 받는데 작은 화면으로 많은 정보를 넣는 것이 시간을 많이 소요합니다. 편의성 측면에서 리로드 버튼 같은 것이 필요할 것 같습니다.
- 설정 버튼을 누르면 모든 정보가 지워집니다.
  - 기존에 작성한 정보들이 그대로 남아 있었으면 좋겠습니다.
- 화면이 너무 쉽게 꺼집니다.
  - 워치가 위를 보고 있다가 큐알을 사용하기 위해서 아래를 바라보면 손목이 돌아가면서 화면이 자동으로 꺼집니다. 해당 부분은 워치에서 제어가능한지 확인이 필요할 것 같습니다.
- 비밀번호가 노출되기 쉽습니다.
  - 비밀번호를 입력할 때 *** 형태로 찍히고 마지막 문자만 보이면 좋겠는데 평문으로 다 보여서 개인정보가 노출되기 쉬운것 같습니다. 해당부분 수정 가능한지 확인 부탁드립니다.
 
이상입니다.

**Comment by mirusu400** [comment]
* 큐알 코드 갱신이 너무 어렵습니다.
=> 1분단위로 큐알코드가 Expire되서 1분 지나면 새로운 QR을 갱신하던지, 화면을 터치하면 QR갱신하는 방향으로 수정하면 될것같습니다

**Comment by yjyoon-dev** [comment]
- 사용자가 만료 시간 내에 QR 코드를 찍고 앱을 종료할 것을 예상했으나, 백그라운드에 유지시키는 사용자들이 있어 말씀하신대로 QR 코드 화면에서 바로 갱신할 수 있는 기능을 추가할 예정입니다.
- 갤럭시 워치에는 Tilt to sleep 이라는 이름의 기능이 있는데, 이는 기기의 절전을 위해 사용자가 팔을 내려놓을 시 자동으로 화면을 끄거나 AOD로 전환하는 기능입니다. 시스템 상에서도 해당 기능을 끌 수 없기 때문에, 해당 앱이 AOD를 지원하게 하는 방식 등으로 수정 및 테스트를 해 볼 예정입니다.
- 그 외 마이너한 이슈들은 수정 예정에 있습니다.

**Comment by yjyoon-dev** [comment]
다음과 같은 반영사항으로 본 이슈는 close 하도록 하겠습니다. 감사합니다.

- QR 코드 터치 시 새로고침 by @yjyoon-dev in https://github.com/yjyoon-dev/kw-library-wearos/pull/16
- QR 코드 화면에 대해 ambient mode 대응 by @yjyoon-dev in https://github.com/yjyoon-dev/kw-library-wearos/pull/18
